import { useEffect, useState } from 'react';
import { getSales } from '../../api/index';
import { PageHeader, Spinner, SearchInput, EmptyState } from '../../components/UI';
import { ShoppingBag, Download, TrendingUp, Wallet } from 'lucide-react';

const MOCK = Array.from({ length: 10 }, (_, i) => ({
  sale_id: i + 1, 
  invoice_number: `CRZ-20241${i + 1}00`,
  customer_name: `Customer ${i + 1}`, 
  contact_number: `9876${500000 + i}`,
  brand_name: ['Samsung', 'Apple', 'Dell'][i % 3], 
  model_name: ['Galaxy S23', 'iPhone 15', 'Inspiron'][i % 3],
  sale_price: [12000, 75000, 55000][i % 3],
  dealer_commission: [180, 900, 700][i % 3],
  distributor_commission: [90, 450, 350][i % 3],
  plan_years: [1, 2][i % 2],
  dealer_shop: `Shop ${(i % 4) + 1}`,
  warranty_end: `202${5 + (i % 2)}-01-15`,
  sale_date: new Date(Date.now() - i * 86400000).toLocaleDateString(),
}));

export default function DistributorSales() {
  // --- State ---
  const [sales, setSales]       = useState([]);
  const [filtered, setFiltered] = useState([]);
  const [loading, setLoading]   = useState(true);
  const [search, setSearch]     = useState('');

  // --- Data Fetching ---
  useEffect(() => {
    getSales()
      .then(r => { setSales(r.data); setFiltered(r.data); })
      .catch(() => { setSales(MOCK); setFiltered(MOCK); })
      .finally(() => setLoading(false));
  }, []);

  // --- Search Filtering ---
  useEffect(() => {
    const q = search.toLowerCase();
    setFiltered(sales.filter(s => 
      s.invoice_number?.toLowerCase().includes(q) || 
      s.customer_name?.toLowerCase().includes(q) || 
      s.dealer_shop?.toLowerCase().includes(q) ||
      s.brand_name?.toLowerCase().includes(q)
    ));
  }, [search, sales]);

  // --- Calculations ---
  const totalVolume = filtered.reduce((s, x) => s + Number(x.sale_price || 0), 0);
  const totalDist   = filtered.reduce((s, x) => s + Number(x.distributor_commission || 0), 0);

  // --- Export Functionality ---
  const exportCSV = () => {
    const rows = [
      ['Invoice', 'Product', 'Customer', 'Dealer', 'Sale Price', 'My Commission', 'Warranty End', 'Date'],
      ...filtered.map(s => [
        s.invoice_number,
        `${s.brand_name} ${s.model_name}`,
        s.customer_name,
        s.dealer_shop,
        s.sale_price,
        s.distributor_commission,
        s.warranty_end,
        s.sale_date
      ])
    ];
    const csv = rows.map(r => r.join(',')).join('\n');
    const a = document.createElement('a'); 
    a.href = 'data:text/csv,' + encodeURIComponent(csv); 
    a.download = 'distributor_network_sales.csv'; 
    a.click();
  };

  // --- Render ---
  if (loading) return (
    <div className="min-h-[60vh] flex items-center justify-center">
      <Spinner />
    </div>
  );

  return (
    <div className="animate-fade-up font-sans">
      
      {/* Header */}
      <PageHeader 
        title="Network Sales" 
        subtitle="Track sales and commissions generated by your dealer network"
        action={
          <button 
            onClick={exportCSV} 
            className="bg-zinc-800 hover:bg-zinc-700 text-zinc-300 font-medium rounded-xl px-4 py-2.5 transition-all duration-200 border border-zinc-700/50 flex items-center gap-2 text-sm shadow-sm"
          >
            <Download size={16}/> 
            Export CSV
          </button>
        } 
      />

      {/* KPI Summary Cards */}
      <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 mb-6 mt-6">
        {[
          { label: 'Total Network Sales', value: filtered.length,                        icon: ShoppingBag, color: 'text-zinc-100',   bg: 'bg-zinc-900/80 border-zinc-800' },
          { label: 'Total Sales Volume',  value: `₹${totalVolume.toLocaleString()}`,     icon: TrendingUp,  color: 'text-blue-400',   bg: 'bg-blue-500/10 border-blue-500/20' },
          { label: 'My Total Commission', value: `₹${totalDist.toLocaleString()}`,       icon: Wallet,      color: 'text-emerald-400', bg: 'bg-emerald-500/10 border-emerald-500/20' },
        ].map((s, i) => (
          <div key={s.label} className={`rounded-3xl p-6 border backdrop-blur-xl shadow-lg flex items-center gap-4 ${s.bg}`}>
            <div className={`w-12 h-12 rounded-2xl flex items-center justify-center flex-shrink-0 shadow-inner ${
              i === 0 ? 'bg-zinc-800 text-zinc-400' : 
              i === 1 ? 'bg-blue-500/20 text-blue-400' : 
              'bg-emerald-500/20 text-emerald-400'
            }`}>
              <s.icon size={24} />
            </div>
            <div>
              <p className="text-sm text-zinc-400 font-medium mb-0.5">{s.label}</p>
              <p className={`text-2xl font-bold font-mono tracking-tight ${s.color}`}>{s.value}</p>
            </div>
          </div>
        ))}
      </div>

      {/* Search Bar */}
      <div className="mb-6 max-w-md">
        <SearchInput value={search} onChange={setSearch} placeholder="Search by invoice, customer, or dealer..." />
      </div>

      {/* Table Card */}
      <div className="bg-zinc-900/80 backdrop-blur-xl border border-zinc-800 rounded-3xl shadow-xl overflow-hidden">
        {filtered.length === 0 ? (
          <EmptyState 
            icon={ShoppingBag} 
            title="No sales found" 
            description={search ? "Try adjusting your search criteria." : "Your network hasn't recorded any sales yet."} 
          />
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-left border-collapse whitespace-nowrap">
              <thead>
                <tr className="bg-zinc-950/50 border-b border-zinc-800/80 text-zinc-400 text-xs uppercase tracking-wider font-semibold">
                  <th className="px-6 py-4">Invoice</th>
                  <th className="px-6 py-4">Product Details</th>
                  <th className="px-6 py-4">Customer</th>
                  <th className="px-6 py-4">Dealer Shop</th>
                  <th className="px-6 py-4">Sale Price</th>
                  <th className="px-6 py-4">Your Commission</th>
                  <th className="px-6 py-4">Warranty End</th>
                  <th className="px-6 py-4 text-right">Date</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-zinc-800/50">
                {filtered.map(s => (
                  <tr key={s.sale_id} className="hover:bg-zinc-800/20 transition-colors">
                    
                    {/* Invoice */}
                    <td className="px-6 py-4">
                      <span className="inline-flex items-center px-2.5 py-1 rounded-md bg-indigo-500/10 border border-indigo-500/20 text-indigo-400 font-mono text-xs font-semibold">
                        {s.invoice_number}
                      </span>
                    </td>

                    {/* Product */}
                    <td className="px-6 py-4">
                      <p className="font-semibold text-zinc-100">{s.brand_name} {s.model_name}</p>
                      <p className="text-xs text-zinc-400 mt-0.5">{s.plan_years} Year Plan</p>
                    </td>

                    {/* Customer */}
                    <td className="px-6 py-4">
                      <p className="font-medium text-zinc-200">{s.customer_name}</p>
                      <p className="text-xs text-zinc-500 font-mono mt-0.5">{s.contact_number}</p>
                    </td>

                    {/* Dealer Shop */}
                    <td className="px-6 py-4">
                      <span className="inline-flex items-center px-2.5 py-1 rounded-md bg-zinc-800/50 border border-zinc-700/50 text-xs font-medium text-zinc-300">
                        {s.dealer_shop}
                      </span>
                    </td>

                    {/* Sale Price */}
                    <td className="px-6 py-4">
                      <span className="font-mono text-zinc-300">₹{Number(s.sale_price).toLocaleString()}</span>
                    </td>

                    {/* Distributor Commission */}
                    <td className="px-6 py-4">
                      <span className="font-mono font-bold text-emerald-400 bg-emerald-500/10 px-2 py-1 rounded-md">
                        +₹{Number(s.distributor_commission).toLocaleString()}
                      </span>
                    </td>

                    {/* Warranty End */}
                    <td className="px-6 py-4">
                      <span className="text-zinc-400 text-sm font-mono">{s.warranty_end}</span>
                    </td>

                    {/* Date */}
                    <td className="px-6 py-4 text-right">
                      <span className="text-zinc-500 text-sm font-medium">{s.sale_date}</span>
                    </td>

                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>

    </div>
  );
}